Repository Kernel360/E2E2-LOOK-US, pull requests merged in 2024-08, with the labels that each got.

#32 Feature/#30 API 표준 설정 방식 V2 (초안)
  backend/src/main/java/org/example/exception/UserNotFoundException.java
  backend/src/main/java/org/example/exception/common/ApiErrorCategory.java
  backend/src/main/java/org/example/exception/common/ApiErrorResponse.java
  backend/src/main/java/org/example/exception/common/ApiException.java
  backend/src/main/java/org/example/exception/common/ApiExceptionHandler.java
  backend/src/main/java/org/example/exception/post/ApiPostErrorSubCategory.java
  backend/src/main/java/org/example/exception/post/ApiPostException.java
  backend/src/main/java/org/example/exception/post/ApiPostExceptionHandler.java
  backend/src/main/java/org/example/exception/response/ExceptionResponse.java
  backend/src/main/java/org/example/exception/user/ApiUserErrorSubCategory.java
  backend/src/main/java/org/example/exception/user/ApiUserException.java
  backend/src/main/java/org/example/exception/user/ApiUserExceptionHandler.java
Labels: enhancement

#33 [Fix] UserEntity 수정
  backend/schema.sql
  backend/src/main/java/org/example/config/WebOAuthSecurityConfig.java
  backend/src/main/java/org/example/config/jwt/TokenProvider.java
  backend/src/main/java/org/example/config/oauth/OAuth2SuccessHandler.java
  backend/src/main/java/org/example/post/domain/entity/PostEntity.java
  backend/src/main/java/org/example/post/domain/entity/UserPostLikesEntity.java
  backend/src/main/java/org/example/user/application/token/RefreshTokenService.java
  backend/src/main/java/org/example/user/application/token/TokenService.java
  backend/src/main/java/org/example/user/controller/member/UserApiController.java
  backend/src/main/java/org/example/user/controller/member/UserViewController.java
  backend/src/main/java/org/example/user/controller/token/TokenApiController.java
  backend/src/main/java/org/example/user/domain/entity/member/UserEntity.java
  backend/src/main/java/org/example/user/domain/enums/UserStatus.java
  backend/src/main/java/org/example/user/presentation/member/UserApiController.java
  backend/src/main/java/org/example/user/presentation/member/UserViewController.java
  backend/src/main/java/org/example/user/service/member/UserDetailService.java
  backend/src/main/java/org/example/user/service/member/UserService.java
  backend/src/main/java/org/example/user/service/token/RefreshTokenService.java
  backend/src/main/java/org/example/user/service/token/TokenService.java
  backend/src/test/java/org/example/config/jwt/TokenProviderTest.java
  backend/src/test/java/org/example/user/controller/token/TokenApiControllerTest.java
  backend/src/test/java/org/example/user/presentation/token/TokenApiControllerTest.java
Labels: enhancement

#38 [Feat] 전체 게시글 및, 검색 기능 추가
  backend/src/main/java/org/example/common/TimeTrackableDto.java
  backend/src/main/java/org/example/post/common/PostMapper.java
  backend/src/main/java/org/example/post/common/SortProperty.java
  backend/src/main/java/org/example/post/controller/PostApiController.java
  backend/src/main/java/org/example/post/domain/dto/PostResponseDto.java
  backend/src/main/java/org/example/post/domain/dto/request/PaginationRequestDto.java
  backend/src/main/java/org/example/post/domain/dto/request/PostCreateRequestDto.java
  backend/src/main/java/org/example/post/domain/dto/request/SortRequestDto.java
  backend/src/main/java/org/example/post/domain/dto/response/PaginationResponseDto.java
  backend/src/main/java/org/example/post/domain/dto/response/PostResponseDto.java
  backend/src/main/java/org/example/post/domain/entity/PostEntity.java
  backend/src/main/java/org/example/post/repository/PostRepository.java
  backend/src/main/java/org/example/post/service/PostService.java
  backend/src/test/java/org/example/post/service/PostServiceTest.java
Labels: enhancement

#42 [Fix] Entity 수정
  backend/src/main/java/org/example/post/domain/entity/PostEntity.java
  backend/src/main/java/org/example/post/domain/entity/UserPostLikesEntity.java
  backend/src/main/java/org/example/user/domain/entity/member/UserEntity.java
Labels: bug

#44 [feat] Post 상세조회
  backend/.DS_Store
  backend/.gitignore
  backend/src/.DS_Store
  backend/src/main/.DS_Store
  backend/src/main/java/org/example/post/common/PostMapper.java
  backend/src/main/java/org/example/post/controller/PostApiController.java
  backend/src/main/java/org/example/post/domain/dto/response/PaginationResponseDto.java
  backend/src/main/java/org/example/post/domain/dto/response/PostResponseDto.java
  backend/src/main/java/org/example/post/service/PostService.java
  backend/src/test/java/org/example/post/service/PostServiceTest.java
Labels: enhancement

#48 [Feat] 해시태그와 기존 검색어로 게시글 검색 관련 기능 추가 및 수정
  backend/src/main/java/org/example/post/controller/PostApiController.java
  backend/src/main/java/org/example/post/domain/dto/request/PaginationRequestDto.java
  backend/src/main/java/org/example/post/domain/dto/request/PostCreateRequestDto.java
  backend/src/main/java/org/example/post/domain/dto/request/PostRequestDto.java
  backend/src/main/java/org/example/post/domain/dto/request/SortRequestDto.java
  backend/src/main/java/org/example/post/domain/dto/response/PaginationResponseDto.java
  backend/src/main/java/org/example/post/domain/dto/response/PostResponseDto.java
  backend/src/main/java/org/example/post/domain/entity/HashtagEntity.java
  backend/src/main/java/org/example/post/domain/entity/PostEntity.java
  backend/src/main/java/org/example/post/domain/entity/UserPostLikesEntity.java
  backend/src/main/java/org/example/post/repository/PostRepository.java
  backend/src/main/java/org/example/post/service/PostService.java
Labels: enhancement

#63 [Fix] merge 충돌 해결
  backend/src/main/java/org/example/image/storage/FileSystemStorage/FileSystemStorage.java
  backend/src/main/java/org/example/post/controller/PostApiController.java
  backend/src/main/java/org/example/post/domain/dto/PostDto.java
  backend/src/main/java/org/example/post/service/PostService.java
  backend/src/main/java/org/example/user/service/member/UserService.java
  backend/src/main/resources/static/img/github.png
  backend/src/main/resources/static/img/google.png
  backend/src/main/resources/static/js/article.js
  backend/src/main/resources/static/js/token.js
  backend/src/main/resources/templates/article.html
  backend/src/main/resources/templates/articleList.html
  backend/src/main/resources/templates/example.html
  backend/src/main/resources/templates/newArticle.html
  backend/src/main/resources/templates/oauthLogin.html
Labels: bug

#64 [Feat] 게시글 저장 시 게시글 & 해시태그 엔티티 매핑 완료 및 RECORD 로 DTO 업데이트
  backend/src/main/java/org/example/common/TimeTrackableDto.java
  backend/src/main/java/org/example/config/WebOAuthSecurityConfig.java
  backend/src/main/java/org/example/config/oauth/OAuth2UserCustomService.java
  backend/src/main/java/org/example/post/common/PostMapper.java
  backend/src/main/java/org/example/post/common/SortProperty.java
  backend/src/main/java/org/example/post/controller/PostApiController.java
  backend/src/main/java/org/example/post/controller/PostController.java
  backend/src/main/java/org/example/post/domain/dto/PaginationDto.java
  backend/src/main/java/org/example/post/domain/dto/PostDto.java
  backend/src/main/java/org/example/post/domain/dto/request/PaginationRequestDto.java
  backend/src/main/java/org/example/post/domain/dto/request/PostRequestDto.java
  backend/src/main/java/org/example/post/domain/dto/response/PaginationResponseDto.java
  backend/src/main/java/org/example/post/domain/dto/response/PostResponseDto.java
  backend/src/main/java/org/example/post/domain/entity/HashtagEntity.java
  backend/src/main/java/org/example/post/domain/entity/PostEntity.java
  backend/src/main/java/org/example/post/repository/HashtagRepository.java
  backend/src/main/java/org/example/post/repository/PostRepository.java
  backend/src/main/java/org/example/post/service/PostService.java
  backend/src/main/resources/static/img/github.png
  backend/src/main/resources/static/img/google.png
  backend/src/main/resources/static/js/article.js
  backend/src/main/resources/static/js/token.js
  backend/src/main/resources/templates/articleList.html
  backend/src/main/resources/templates/example.html
  backend/src/main/resources/templates/newArticle.html
  backend/src/main/resources/templates/oauthLogin.html
Labels: enhancement

#69 [Fix] getpostdtoresponse, createpost에서 valid 수정
  backend/src/main/java/org/example/post/controller/PostApiController.java
  backend/src/main/java/org/example/post/domain/dto/PostDto.java
Labels: documentation

#75 [Feat] ImageResourceController의 handleImageUpload 테스트 코드
  backend/src/main/java/org/example/config/WebOAuthSecurityConfig.java
  backend/src/test/java/org/example/image/controller/ImageResourceControllerTest.java
Labels: enhancement

#83 [Refactor] Post querydsl 및 controller 리팩토링
  backend/src/main/java/org/example/config/WebOAuthSecurityConfig.java
  backend/src/main/java/org/example/post/controller/PostApiController.java
  backend/src/main/java/org/example/post/controller/PostPublicController.java
  backend/src/main/java/org/example/post/domain/dto/PostDto.java
  backend/src/main/java/org/example/post/repository/custom/PostRepositoryImpl.java
  backend/src/main/java/org/example/post/repository/custom/PostSearchCondition.java
  backend/src/main/java/org/example/post/service/PostService.java
Labels: duplicate

#91 [Fix] README 수정
  LOOKUS_대표이미지.jpg
  README.md
Labels: documentation

#102 [Feat] 마이페이지 추가
  backend/src/main/java/org/example/config/oauth/OAuth2SuccessHandler.java
  backend/src/main/java/org/example/exception/user/ApiUserErrorSubCategory.java
  backend/src/main/java/org/example/post/domain/dto/PostDto.java
  backend/src/main/java/org/example/post/repository/custom/PostRepositoryImpl.java
  backend/src/main/java/org/example/post/repository/custom/PostSearchCondition.java
  backend/src/main/java/org/example/user/controller/member/UserApiController.java
  backend/src/main/java/org/example/user/domain/dto/UserDto.java
  backend/src/main/java/org/example/user/domain/entity/member/UserEntity.java
  backend/src/main/java/org/example/user/domain/enums/UserStatus.java
  backend/src/main/java/org/example/user/repository/member/UserRepository.java
  backend/src/main/java/org/example/user/repository/member/custom/UserRepositoryCustom.java
  backend/src/main/java/org/example/user/repository/member/custom/UserRepositoryImpl.java
  backend/src/main/java/org/example/user/service/member/UserService.java
  backend/src/test/java/org/example/post/controller/PostControllerTest.java
  backend/src/test/java/org/example/post/controller/PostPublicControllerTest.java
  backend/src/test/java/org/example/post/service/PostServiceTest.java
  backend/src/test/java/org/example/user/controller/member/UserApiControllerTest.java
  backend/src/test/java/org/example/user/domain/entity/member/UserEntityTest.java
Labels: enhancement

#101 [FEAT] 게시물 무한 스크롤 구현, 회원가입/마이페이지 화면만 구현 [#100]
  backend/src/main/java/org/example/follow/controller/FollowController.java
  backend/src/main/java/org/example/follow/domain/dto/FollowRequestDto.java
  backend/src/main/java/org/example/follow/domain/dto/FollowResponseDto.java
  backend/src/main/java/org/example/follow/domain/enums/FollowStatus.java
  backend/src/main/java/org/example/follow/repository/FollowRepository.java
  backend/src/main/java/org/example/follow/service/FollowService.java
  backend/src/main/java/org/example/user/repository/member/UserRepository.java
  frontend/next.config.mjs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/(after-login)/layout.tsx
  frontend/src/app/(after-login)/mypage/components/album-artwork.tsx
  frontend/src/app/(after-login)/mypage/components/mypageinfo.tsx
  frontend/src/app/(after-login)/mypage/data/albums.ts
  frontend/src/app/(after-login)/mypage/data/playlists.ts
  frontend/src/app/(after-login)/mypage/page.tsx
  frontend/src/app/(after-login)/posts/[post_id]/Post.module.scss
  frontend/src/app/(after-login)/posts/gallery.scss
  frontend/src/app/(after-login)/posts/loading.tsx
  frontend/src/app/(after-login)/posts/new/page.tsx
  frontend/src/app/(after-login)/posts/page.tsx
  frontend/src/app/(after-login)/posts/useIntersectionObserver.tsx
  frontend/src/app/(after-login)/settings/account/account-form.tsx
  frontend/src/app/(after-login)/settings/account/page.tsx
  frontend/src/app/(after-login)/settings/appearance/appearance-form.tsx
  frontend/src/app/(after-login)/settings/appearance/page.tsx
  frontend/src/app/(after-login)/settings/components/sidebar-nav.tsx
  frontend/src/app/(after-login)/settings/display/display-form.tsx
  frontend/src/app/(after-login)/settings/display/page.tsx
  frontend/src/app/(after-login)/settings/layout.tsx
  frontend/src/app/(after-login)/settings/notifications/notifications-form.tsx
  frontend/src/app/(after-login)/settings/notifications/page.tsx
  frontend/src/app/(after-login)/settings/page.tsx
  frontend/src/app/(after-login)/settings/profile-form.tsx
  frontend/src/app/(without-login)/layout.tsx
  frontend/src/app/_api/fetchStyle.ts
  frontend/src/app/favicon.ico
  frontend/src/app/globals.css
  frontend/src/components/bottom-control-bar.tsx
  frontend/src/components/ui/checkbox.tsx
  frontend/src/components/ui/context-menu.tsx
  frontend/src/components/ui/menubar.tsx
  frontend/src/components/ui/radio-group.tsx
  frontend/src/components/ui/scroll-area.tsx
  frontend/src/components/ui/switch.tsx
  frontend/src/components/ui/tabs.tsx
Labels: enhancement

#110 Follow, UserService 리팩토링
  backend/src/main/java/org/example/exception/user/ApiUserErrorSubCategory.java
  backend/src/main/java/org/example/follow/controller/FollowApiController.java
  backend/src/main/java/org/example/follow/controller/FollowController.java
  backend/src/main/java/org/example/follow/controller/FollowPublicController.java
  backend/src/main/java/org/example/follow/service/FollowService.java
  backend/src/main/java/org/example/image/storage/core/StorageType.java
  backend/src/main/java/org/example/user/service/member/UserService.java
Labels: enhancement

#111 서비스, 컨트롤러, DTO 등 전체적인 리팩토링
  backend/src/main/java/org/example/config/oauth/OAuth2SuccessHandler.java
  backend/src/main/java/org/example/config/oauth/OAuth2UserCustomService.java
  backend/src/main/java/org/example/exception/post/ApiPostErrorSubCategory.java
  backend/src/main/java/org/example/exception/user/ApiUserErrorSubCategory.java
  backend/src/main/java/org/example/follow/controller/FollowApiController.java
  backend/src/main/java/org/example/follow/domain/dto/FollowDto.java
  backend/src/main/java/org/example/follow/domain/dto/FollowRequestDto.java
  backend/src/main/java/org/example/follow/domain/dto/FollowResponseDto.java
  backend/src/main/java/org/example/follow/repository/FollowRepository.java
  backend/src/main/java/org/example/follow/service/FollowService.java
  backend/src/main/java/org/example/post/controller/PostApiController.java
  backend/src/main/java/org/example/post/domain/entity/PostEntity.java
  backend/src/main/java/org/example/post/service/PostService.java
  backend/src/main/java/org/example/user/controller/member/UserApiController.java
  backend/src/main/java/org/example/user/controller/member/UserViewController.java
  backend/src/main/java/org/example/user/domain/entity/member/UserEntity.java
  backend/src/main/java/org/example/user/service/member/UserService.java
  backend/src/main/java/org/example/user/service/token/RefreshTokenService.java
  backend/src/main/java/org/example/user/service/token/TokenService.java
  backend/src/test/java/org/example/user/controller/member/UserViewControllerTest.java
  backend/src/test/java/org/example/user/domain/entity/member/UserEntityTest.java
  backend/src/test/java/org/example/user/service/member/UserServiceTest.java
Labels: enhancement

#112 [feat] 마이페이지 포스트 부분, 팔로우 부분, 이미지 변경 기능
  backend/src/main/java/org/example/post/controller/PostPublicController.java
  backend/src/main/java/org/example/user/domain/dto/UserDto.java
  backend/src/main/java/org/example/user/repository/member/custom/UserRepositoryImpl.java
  frontend/next.config.mjs
  frontend/src/app/(after-login)/mypage/components/PostCard.tsx
  frontend/src/app/(after-login)/mypage/components/ProfileImageModal.tsx
  frontend/src/app/(after-login)/mypage/components/album-artwork.tsx
  frontend/src/app/(after-login)/mypage/components/mypageinfo.tsx
  frontend/src/app/(after-login)/mypage/data/albums.ts
  frontend/src/app/(after-login)/mypage/data/playlists.ts
  frontend/src/app/(after-login)/mypage/page.tsx
  frontend/src/app/(after-login)/posts/[post_id]/Post.module.scss
  frontend/src/app/(after-login)/posts/[post_id]/page.tsx
  frontend/src/app/(after-login)/posts/new/page.tsx
  frontend/src/app/(after-login)/posts/page.tsx
  frontend/src/app/(without-login)/layout.tsx
  frontend/src/app/_api/fetchStyle.ts
  frontend/src/app/_api/follow.ts
  frontend/src/app/_api/myPage.ts
  frontend/src/app/_api/myPost.ts
  frontend/src/app/_api/post.ts
  frontend/src/app/globals.css
Labels: enhancement

#117 Fix/#116/pagination sort
  backend/src/main/java/org/example/post/domain/dto/PostDto.java
  backend/src/main/java/org/example/post/repository/custom/PostRepositoryImpl.java
Labels: bug

#120 [Feat] RGB 변환기, Base64 인코더 구현
  backend/src/main/java/org/example/image/tools/Base64Converter.java
  backend/src/main/java/org/example/image/tools/ColorConverter.java
  backend/src/main/java/org/example/image/tools/LabColorCode.java
  backend/src/main/java/org/example/image/tools/LabColorSimilarity.java
  backend/src/test/java/org/example/image/tools/Base64ConverterTest.java
  backend/src/test/java/org/example/image/tools/LabColorSimilarityTest.java
  backend/src/test/java/org/example/post/controller/PostPublicControllerTest.java
  backend/src/test/java/org/example/user/controller/member/UserApiControllerTest.java
Labels: enhancement

#125 feat: (FE) 컬러피커(카테고리별), 마이페이지 수정, 회원가입 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/(after-login)/color-selection/page.tsx
  frontend/src/app/(after-login)/layout.tsx
  frontend/src/app/(after-login)/mypage/components/FollowListModal.tsx
  frontend/src/app/(after-login)/mypage/components/PostCard.tsx
  frontend/src/app/(after-login)/mypage/components/ProfileImageModal.scss
  frontend/src/app/(after-login)/mypage/components/ProfileImageModal.tsx
  frontend/src/app/(after-login)/mypage/components/followlistmodal.scss
  frontend/src/app/(after-login)/mypage/components/mypageinfo.scss
  frontend/src/app/(after-login)/mypage/components/mypageinfo.tsx
  frontend/src/app/(after-login)/mypage/components/postcard.scss
  frontend/src/app/(after-login)/mypage/mypage.scss
  frontend/src/app/(after-login)/mypage/page.tsx
  frontend/src/app/(after-login)/posts/page.tsx
  frontend/src/app/(without-login)/layout.tsx
  frontend/src/app/(without-login)/signup/layout.tsx
  frontend/src/app/(without-login)/signup/page.tsx
  frontend/src/app/(without-login)/signup/signup.scss
  frontend/src/app/_api/myPage.ts
  frontend/src/components/search-bar.tsx
Labels: enhancement

#129 [Feat] 초기 연예인 데이터 수집용 웹 크롤링
  ImageWebCrawling.R
  backend/.gitignore
Labels: documentation, enhancement

#138 [Feat] 광원 TRISTIMULUS 검토, 색 ENUM 검토 및 Redis 세팅
  backend/PostCreateLogic.excalidraw
  backend/PostCreateLogic.jpg
  backend/image.excalidraw
  backend/imageFlow.jpg
  backend/src/main/java/org/example/config/WebOAuthSecurityConfig.java
  backend/src/main/java/org/example/config/redis/RedisConfig.java
  backend/src/main/java/org/example/image/ImageAnalyzeManager/ImageAnalyzeManager.java
  backend/src/main/java/org/example/image/ImageAnalyzeManager/ImageAnalyzeManagerImpl/ImageAnalyzeManagerImpl.java
  backend/src/main/java/org/example/image/ImageAnalyzeManager/analyzer/service/GoogleImagenVisionService/GoogleImagenVisionService.java
  backend/src/main/java/org/example/image/ImageAnalyzeManager/analyzer/tools/ColorConverter.java
  backend/src/main/java/org/example/image/ImageAnalyzeManager/analyzer/tools/LabColorCode.java
  backend/src/main/java/org/example/image/ImageAnalyzeManager/analyzer/tools/LabColorConverter.java
  backend/src/main/java/org/example/image/ImageAnalyzeManager/analyzer/tools/LabColorSimilarity.java
  backend/src/main/java/org/example/image/ImageAnalyzeManager/analyzer/type/ClothAnalyzeData.java
  backend/src/main/java/org/example/image/ImageAnalyzeManager/analyzer/type/LabColor.java
  backend/src/main/java/org/example/image/ImageAnalyzeManager/analyzer/type/NormalizedVertex2D.java
  backend/src/main/java/org/example/image/ImageAnalyzeManager/analyzer/type/RGBColor.java
  backend/src/main/java/org/example/image/controller/ImageApiController.java
  backend/src/main/java/org/example/image/redis/ColorApiClient.java
  backend/src/main/java/org/example/image/redis/domain/dto/ColorDto.java
  backend/src/main/java/org/example/image/redis/domain/dto/ColorInfoResponse.java
  backend/src/main/java/org/example/image/redis/domain/entity/ColorEntity.java
  backend/src/main/java/org/example/image/redis/repository/ImageRedisRepository.java
  backend/src/main/java/org/example/image/redis/service/ImageRedisService.java
  backend/src/main/java/org/example/image/redis/tools/RgbColorSimilarity.java
  backend/src/main/java/org/example/post/repository/PostRepository.java
  backend/src/main/java/org/example/post/repository/custom/PostPopularSearchCondition.java
  backend/src/main/java/org/example/post/repository/custom/PostRepositoryImpl.java
  backend/src/main/java/org/example/post/service/PostService.java
Labels: enhancement

#179 feat: 비로그인 유저 접근 제한기능(FE)
  frontend/middleware.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/public/images/android-icon-144x144.png
  frontend/public/images/android-icon-192x192.png
  frontend/public/images/android-icon-36x36.png
  frontend/public/images/android-icon-48x48.png
  frontend/public/images/android-icon-512x512.png
  frontend/public/images/android-icon-72x72.png
  frontend/public/images/android-icon-96x96.png
  frontend/public/manifest.json
  frontend/public/sw.js
  frontend/public/sw.js.map
  frontend/public/workbox-e43f5367.js
  frontend/public/workbox-e43f5367.js.map
  frontend/src/app/(after-login)/color-selection/page.tsx
  frontend/src/app/(after-login)/mypage/components/ProfileEditPage.tsx
  frontend/src/app/(after-login)/mypage/components/mypageinfo.scss
  frontend/src/app/(after-login)/mypage/components/mypageinfo.tsx
  frontend/src/app/(after-login)/mypage/components/profileeditpage.scss
  frontend/src/app/(after-login)/mypage/edit/page.tsx
  frontend/src/app/(after-login)/mypage/page.tsx
  frontend/src/app/(after-login)/posts/[post_id]/Post.module.scss
  frontend/src/app/(after-login)/posts/[post_id]/page.tsx
  frontend/src/app/(after-login)/posts/[post_id]/useTheme.ts
  frontend/src/app/(after-login)/posts/new/page.tsx
  frontend/src/app/(after-login)/settings/account/account-form.tsx
  frontend/src/app/(after-login)/settings/account/page.tsx
  frontend/src/app/(after-login)/settings/appearance/appearance-form.tsx
  frontend/src/app/(after-login)/settings/appearance/page.tsx
  frontend/src/app/(after-login)/settings/components/sidebar-nav.tsx
  frontend/src/app/(after-login)/settings/display/display-form.tsx
  frontend/src/app/(after-login)/settings/display/page.tsx
  frontend/src/app/(after-login)/settings/layout.tsx
  frontend/src/app/(after-login)/settings/notifications/notifications-form.tsx
  frontend/src/app/(after-login)/settings/notifications/page.tsx
  frontend/src/app/(after-login)/settings/page.tsx
  frontend/src/app/(after-login)/settings/profile-form.tsx
  frontend/src/app/(after-login)/settings/profileEdit.scss
  frontend/src/app/(without-login)/login/LoginPage.scss
  frontend/src/app/(without-login)/login/layout.tsx
  frontend/src/app/(without-login)/login/page.tsx
  frontend/src/app/(without-login)/signup/page.tsx
  frontend/src/app/(without-login)/signup/signup.scss
  frontend/src/app/_api/fetchStyle.ts
  frontend/src/app/_api/post.ts
  frontend/src/app/_common/constants.ts
  frontend/src/components/BottomControlBar.scss
  frontend/src/components/modal-accesscontrol.tsx
  frontend/src/components/post-preview.tsx
  frontend/src/components/profile-image-modal.tsx
  frontend/src/components/profileImageModal.scss
Labels: enhancement

#192 feat:category 작업 완료(BE)
  backend/src/main/java/org/example/post/controller/PostApiController.java
  backend/src/main/java/org/example/post/controller/PostPublicController.java
  backend/src/main/java/org/example/post/domain/dto/PostDto.java
  backend/src/main/java/org/example/post/domain/entity/CategoryEntity.java
  backend/src/main/java/org/example/post/domain/entity/PostEntity.java
  backend/src/main/java/org/example/post/repository/CategoryRepository.java
  backend/src/main/java/org/example/post/repository/PostRepository.java
  backend/src/main/java/org/example/post/repository/custom/PostRepositoryImpl.java
  backend/src/main/java/org/example/post/repository/custom/PostSearchCondition.java
  backend/src/main/java/org/example/post/service/PostService.java
  backend/src/main/java/org/example/post/service/PostStatsService.java
Labels: enhancement

#198 fix: 게시글 검색 - GET에 맞게 쿼리파라미터로 변경
  backend/src/main/java/org/example/post/controller/PostPublicController.java
  frontend/src/app/(after-login)/color-selection/page.tsx
  frontend/src/app/(after-login)/mypage/page.tsx
  frontend/src/app/(after-login)/posts/new/page.tsx
  frontend/src/app/(after-login)/settings/page.tsx
Labels: bug

#206 fix: imageResource관련 에러 해결, 프론트 작업중
  backend/src/main/java/org/example/config/TokenAuthenticationFilter.java
  backend/src/main/java/org/example/config/WebOAuthSecurityConfig.java
  backend/src/main/java/org/example/post/controller/PostPublicController.java
  backend/src/main/java/org/example/post/domain/entity/CategoryEntity.java
  backend/src/main/java/org/example/post/repository/custom/PostRepositoryImpl.java
  backend/src/main/java/org/example/post/service/PostService.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/(after-login)/mypage/page.tsx
  frontend/src/app/(after-login)/posts/new/page.tsx
  frontend/src/app/(after-login)/settings/page.tsx
  frontend/src/app/_api/fetchStyle.ts
  frontend/src/app/_api/myPage.ts
  frontend/src/app/_api/post.ts
  frontend/src/app/_api/useAuth.ts
  frontend/src/components/post-create.tsx
  frontend/src/components/post-preview.tsx
Labels: bug

#218 fix:FE build 전 세팅 해결
  frontend/src/app/(after-login)/mypage/page.tsx
  frontend/src/components/image-editor/image-editor.tsx
Labels: bug

#227 [Feat] Custom Annotation 으로 로깅 처리
  backend/build.gradle
  backend/src/main/java/org/example/config/TokenAuthenticationFilter.java
  backend/src/main/java/org/example/config/WebOAuthSecurityConfig.java
  backend/src/main/java/org/example/config/batch/BatchScheduler.java
  backend/src/main/java/org/example/config/batch/UpdatePostStatsTasklet.java
  backend/src/main/java/org/example/config/jwt/TokenProvider.java
  backend/src/main/java/org/example/config/oauth/OAuth2AuthorizationRequestBasedOnCookieRepository.java
  backend/src/main/java/org/example/config/oauth/OAuth2SuccessHandler.java
  backend/src/main/java/org/example/config/oauth/OAuth2UserCustomService.java
  backend/src/main/java/org/example/config/redis/RedisInitializer.java
  backend/src/main/java/org/example/follow/controller/FollowApiController.java
  backend/src/main/java/org/example/follow/controller/FollowPublicController.java
  backend/src/main/java/org/example/follow/service/FollowService.java
  backend/src/main/java/org/example/image/AsyncImageAnalyzer.java
  backend/src/main/java/org/example/image/ImageAnalyzeManager/ImageAnalyzeManagerImpl/ImageAnalyzeManagerImpl.java
  backend/src/main/java/org/example/image/ImageAnalyzeManager/analyzer/service/GoogleImagenVisionService/GoogleImagenVisionService.java
  backend/src/main/java/org/example/image/ImageAnalyzeManager/analyzer/service/GoogleImagenVisionService/utils/ClothTypeMapper.java
  backend/src/main/java/org/example/image/controller/ImageApiController.java
  backend/src/main/java/org/example/image/imageStorageManager/imageStorageManagerImpl/ImageStorageManagerImpl.java
  backend/src/main/java/org/example/image/imageStorageManager/storage/controller/ImageApiResourceController.java
  backend/src/main/java/org/example/image/imageStorageManager/storage/controller/ImagePublicResourceController.java
  backend/src/main/java/org/example/image/redis/ColorApiClient.java
  backend/src/main/java/org/example/image/redis/service/ImageRedisService.java
  backend/src/main/java/org/example/log/AppConfig.java
  backend/src/main/java/org/example/log/LogAspect.java
  backend/src/main/java/org/example/log/LogExecution.java
  backend/src/main/java/org/example/post/controller/PostPublicController.java
  backend/src/main/java/org/example/post/repository/custom/LikeRepositoryImpl.java
  backend/src/main/java/org/example/post/repository/custom/PostRepositoryImpl.java
  backend/src/main/java/org/example/post/service/PostService.java
  backend/src/main/java/org/example/post/service/PostStatsService.java
  backend/src/main/java/org/example/scrap/controller/ScrapController.java
  backend/src/main/java/org/example/scrap/service/ScrapService.java
  backend/src/main/java/org/example/user/controller/member/UserApiController.java
  backend/src/main/java/org/example/user/controller/member/UserViewController.java
  backend/src/main/java/org/example/user/controller/token/TokenApiController.java
  backend/src/main/java/org/example/user/repository/member/custom/UserRepositoryImpl.java
  backend/src/main/java/org/example/user/service/member/UserDetailService.java
  backend/src/main/java/org/example/user/service/member/UserService.java
  backend/src/main/java/org/example/user/service/token/RefreshTokenService.java
  backend/src/main/java/org/example/user/service/token/TokenService.java
  backend/src/main/java/org/example/util/CookieUtil.java
  backend/src/main/java/org/example/validation/annotation/CustomEmail.java
  backend/src/main/java/org/example/validation/validator/CustomEmailValidator.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/log4j2.xml
Labels: documentation, enhancement

#235 fix 카테고리 + 색상 기반 검색 에러 수정
  backend/.gitignore
  backend/src/main/java/org/example/post/controller/PostPublicController.java
  backend/src/main/java/org/example/post/repository/CategoryRepository.java
  backend/src/main/java/org/example/post/repository/PostRepository.java
  backend/src/main/java/org/example/post/repository/custom/CategoryAndColorSearchCondition.java
  backend/src/main/java/org/example/post/repository/custom/PostRepositoryCustom.java
  backend/src/main/java/org/example/post/repository/custom/PostRepositoryImpl.java
  backend/src/main/java/org/example/post/service/PostService.java
Labels: bug

#244 [Feat] 색 검색 시 추천 RGB
  backend/src/main/java/org/example/image/redis/domain/dto/ColorDto.java
  backend/src/main/java/org/example/image/redis/service/ImageRedisService.java
  backend/src/main/java/org/example/post/controller/PostPublicController.java
Labels: enhancement

#259 [feat] 테스트 코드
  backend/src/main/java/org/example/exception/storage/ApiStorageException.java
  backend/src/main/java/org/example/image/AsyncImageAnalyzePipeline.java
  backend/src/main/java/org/example/image/ImageAnalyzeManager/analyzer/service/GoogleImagenVisionService/GoogleImagenVisionService.java
  backend/src/main/java/org/example/image/ImageAnalyzeManager/analyzer/service/GoogleImagenVisionService/utils/GoogleApiCredentialRoller.java
  backend/src/main/java/org/example/image/ImageAnalyzeManager/analyzer/tools/ColorConverter.java
  backend/src/main/java/org/example/image/ImageAnalyzeManager/analyzer/tools/ImageCropper.java
  backend/src/main/java/org/example/image/ImageAnalyzeManager/analyzer/tools/LabColorSimilarity.java
  backend/src/main/java/org/example/image/imageStorageManager/storage/service/FileSystemStorage/FileSystemStorage.java
  backend/src/main/java/org/example/image/redis/service/ImageRedisService.java
  backend/src/test/java/org/example/blog/presentation/article/BlogApiControllerTest.java
  backend/src/test/java/org/example/config/jwt/JwtFactory.java
  backend/src/test/java/org/example/config/jwt/TokenProviderTest.java
  backend/src/test/java/org/example/image/AsyncImageAnalyzePipelineTest.java
  backend/src/test/java/org/example/image/ImageAnalyzeManager/ImageAnalyzeManagerImpl/ImageAnalyzeManagerImplTest.java
  backend/src/test/java/org/example/image/ImageAnalyzeManager/analyzer/entity/ClothAnalyzeDataEntityTest.java
  backend/src/test/java/org/example/image/ImageAnalyzeManager/analyzer/entity/QClothAnalyzeDataEntityTest.java
  backend/src/test/java/org/example/image/ImageAnalyzeManager/analyzer/service/GoogleImagenVisionService/GoogleImagenVisionServiceTest.java
  backend/src/test/java/org/example/image/ImageAnalyzeManager/analyzer/service/GoogleImagenVisionService/type/GoogleImagenVisionDtoTest.java
  backend/src/test/java/org/example/image/ImageAnalyzeManager/analyzer/service/GoogleImagenVisionService/utils/ClothTypeMapperTest.java
  backend/src/test/java/org/example/image/ImageAnalyzeManager/analyzer/service/GoogleImagenVisionService/utils/GoogleApiCredentialRollerTest.java
  backend/src/test/java/org/example/image/ImageAnalyzeManager/analyzer/tools/Base64ConverterTest.java
  backend/src/test/java/org/example/image/ImageAnalyzeManager/analyzer/tools/ColorConverterTest.java
  backend/src/test/java/org/example/image/ImageAnalyzeManager/analyzer/tools/ImageCropperTest.java
  backend/src/test/java/org/example/image/ImageAnalyzeManager/analyzer/tools/LabColorConverterTest.java
  backend/src/test/java/org/example/image/ImageAnalyzeManager/analyzer/tools/LabColorSimilarityTest.java
  backend/src/test/java/org/example/image/ImageAnalyzeManager/analyzer/type/ClothAnalyzeDataTest.java
  backend/src/test/java/org/example/image/ImageAnalyzeManager/analyzer/type/ClothTypeTest.java
  backend/src/test/java/org/example/image/ImageAnalyzeManager/analyzer/type/LabColorTest.java
  backend/src/test/java/org/example/image/ImageAnalyzeManager/analyzer/type/NormalizedVertex2DTest.java
  backend/src/test/java/org/example/image/ImageAnalyzeManager/analyzer/type/RGBColorTest.java
  backend/src/test/java/org/example/image/ImageAnalyzeManager/type/ImageAnalyzeDataTest.java
  backend/src/test/java/org/example/image/controller/ImageApiControllerTest.java
  backend/src/test/java/org/example/image/controller/ImageResourceControllerTest.java
  backend/src/test/java/org/example/image/imageStorageManager/imageStorageManagerImpl/ImageStorageManagerImplTest.java
  backend/src/test/java/org/example/image/imageStorageManager/storage/controller/ImageApiResourceControllerTest.java
  backend/src/test/java/org/example/image/imageStorageManager/storage/controller/ImagePublicResourceControllerTest.java
  backend/src/test/java/org/example/image/imageStorageManager/storage/entity/QImageLocationEntityTest.java
  backend/src/test/java/org/example/image/imageStorageManager/storage/service/FileSystemStorage/FileSystemStorageTest.java
  backend/src/test/java/org/example/image/redis/domain/dto/ColorDtoTest.java
  backend/src/test/java/org/example/image/redis/domain/dto/ColorInfoResponseTest.java
  backend/src/test/java/org/example/image/redis/domain/entity/ColorEntityTest.java
  backend/src/test/java/org/example/image/redis/service/ImageRedisServiceTest.java
  backend/src/test/java/org/example/image/tools/Base64ConverterTest.java
  backend/src/test/java/org/example/image/tools/LabColorSimilarityTest.java
  backend/src/test/java/org/example/post/controller/PostPublicControllerTest.java
  backend/src/test/java/org/example/post/service/PostServiceTest.java
  backend/src/test/java/org/example/user/controller/member/UserApiControllerTest.java
  backend/src/test/java/org/example/user/controller/member/UserViewControllerTest.java
  backend/src/test/java/org/example/user/controller/token/TokenApiControllerTest.java
  backend/src/test/java/org/example/user/domain/entity/member/UserEntityTest.java
  backend/src/test/java/org/example/user/service/member/UserDetailServiceTest.java
  backend/src/test/java/org/example/user/service/member/UserServiceTest.java
  backend/src/test/resources/test_image.jpg
Labels: enhancement

#261 [feat] 메인페이지 UI + 카테고리 기반 검색 + 색상 기반 검색 추가
  frontend/package-lock.json
  frontend/package.json
  frontend/public/images/LOOKUSlogo.png
  frontend/src/app/(after-login)/posts/gallery.module.scss
  frontend/src/app/(after-login)/posts/gallery.scss
  frontend/src/app/(after-login)/posts/page.tsx
  frontend/src/app/_api/category.ts
  frontend/src/components/CategoryList.module.scss
  frontend/src/components/CategoryList.tsx
  frontend/src/components/ColorPickerModal.module.scss
  frontend/src/components/ColorPickerModal.tsx
  frontend/src/components/HeaderSearch.module.scss
  frontend/src/components/post-preview.tsx
  frontend/src/components/search-bar.tsx
Labels: enhancement
